kind: pipeline
name: default
type: docker

steps:
  - name: test-build
    image: alpine
    commands:
      - echo "Hello, Woodpecker!"
      - chmod +x build.sh || true
      - ./build.sh || echo "build.sh failed (ignore if testing)"
