kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: alpine
    commands:
      - chmod +x build.sh || true
      - ./build.sh || echo "Build script failed (probably expected in testing)"
