kind: pipeline
name: default
type: docker

steps:
- name: slack-begin
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    username: Drone
    template: >
      {{repo.name}}/{{build.branch}} - #{{build.number}} Started by {{build.author}} (<{{build.link}}|Open>)

- name: build
  image: node
  commands:
  - npm run build

- name: slack-end
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    username: Drone
    template: >
      {{repo.name}}/{{build.branch}} - #{{build.number}} {{uppercasefirst build.status}} after {{since build.started}} (<{{build.link}}|Open>)
